[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  CI = "false"
  NETLIFY_CACHE_BUST = "2025-08-01-hooks-fix"
  # Dummy Supabase values to prevent initialization errors
  REACT_APP_SUPABASE_URL = "https://dummy.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "dummy-key-for-build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200